REF
mpicc -g -Wall REF.c Lab4_IO.c -o REF -lpthread -lm
mpicc -g -Wall REF2.c Lab4_IO.c -o REF2 -lpthread -lm

mpirun -np 5 ./REF
(number of processes = 5)

serialtester
gcc -g -Wall serialtester.c Lab4_IO.c -o serialtester -lpthread -lm

datatrim
gcc datatrim.c -o datatrim
